### ISSUE TITLE
Would be nice if exports.gracefulExitHandler could take a callback instead of process.exit(0)

### ISSUE THREAD

**Issue by nickminutello** [mmmmmm2/express-graceful-exit#1]
Any chance that exports.gracefulExitHandler could take a callback?
The default behaviour (if callback not supplied) could be to call process.exit when the server closes, but it would be handy to callback to the user for the user to perform any further orderly shutdown tasks.

**Comment by ivolucien** [comment]
mmmmmm2 has given me write permissions and I've merged the 2 PRs (thank you shaharke).  I am now actively maintaining this project moving forward, and am writing fixes for the remaining concerns that nickminutello raises above.

**Comment by shaharke** [comment]
:+1:
